[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "caddy file-server --root build --listen :$PORT"
healthcheckPath = "/"
healthcheckTimeout = 30
