[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "./node_modules/.bin/serve -s build -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 30
